version: "2"

services:
  nsxv3-exporter:
    tty: true
    stdin_open: true
    expose:
      - 9191
    ports:
      - 9191:9191
    image: prom/texp:latest 
    environment:
      - NSXV3_LOGIN_HOST=10.83.24.37
      - NSXV3_LOGIN_PORT=443
      - NSXV3_LOGIN_USER=admin
      - NSXV3_LOGIN_PASSWORD=Admin!23Admin
      - NSXV3_REQUESTS_PER_SECOND=50
      - NSXV3_REQUESTS_PER_SECOND_TIMEOUT=10
      - NSXV3_REQUEST_TIMEOUT_SECONDS=10
      - NSXV3_SUPPRESS_SSL_WARNINGS=true
      - SCRAP_PORT=9191
      - SCRAP_SCHEDULE_SECONDS=5
      - LOG_LEVEL=debug


